### ISSUE TITLE
send later seems to ignore throttleDelay

### ISSUE THREAD

**Issue by fc0** [Extended-Thunder/send-later#503]
"throttleDelay": 600000000,
Still sends all of the unsent messages very quickly...
I am trying to find a way to throttle the sending of mail merges from a CSV file so they don;t overwhelm server requirements.
Some time ago I asked about this and it was identified that this variable could do what was desired.
However, it does not seem to throttle transmissions at all...
Note that sendDelay delays the start of sending but does not perform the throttle function of the pace of transmission.

**Comment by jph-sendlater** [comment]
I'm not able to reproduce this immediately, but I'll do more testing on it when I get some free time.

**Comment by jikamens** [comment]
@jobisoft is it possible that the issue you describe [here](https://github.com/Extended-Thunder/send-later/pull/563#discussion_r1267827354) could be causing multiple schedule scans to happen in parallel, thereby preventing the throttling from working properly?

**Comment by fc0** [comment]
I guess it's possible - but how would I be able to tell, and if true, what could I do about it?

**Comment by jikamens** [comment]
@fc0 I wasn't asking you I was asking the TB developer I tagged ;-)

**Comment by jobisoft** [comment]
Yeah, it looks like the `doSequential` parameter of `possiblySendMessage` did not do anything and the other usage of `throttleDelay` may have been lost in a not awaited call. The PR should fix that.

**Comment by jobisoft** [comment]
Please try this beta. It is a version of send later including PR #563 
[send-later.zip](https://github.com/Extended-Thunder/send-later/files/12139783/send-later.zip)

There is a high chance this fixes also fixes the observed throttle issue.

**Comment by jikamens** [comment]
We believe this issue is resolved in Send Later 9.3.0 for TB109 or 10.0.1 for TB115. Please reopen or comment on the issue if you're still seeing it one of those Send Later versions (or a newer one).

**Comment by fc0** [comment]
Apparently still not fixed:
Now using SL Version 10.3.3 Last Updated October 28, 2023 TB 115.5.0 (64-bit) on Ubuntu up to date
Mail merge from a list (only using a few emails in the list for now).
Sendlater   "throttleDelay": 600000, (I also tried adding another zero with no apparent effect)
Put debugging on Trace and saw nothing helpful - it sent the messages all at once - then said it was waiting 60 seconds 

I am thinking I could simulate this by setting up individual times for each email address in the merge file as a column to put in the send field or some such thing - but that seems a bit too crazy.
Or perhaps I could have an external shell script that somehow pushes a message to be sent into TBird every minute or so?
Any other suggestions or work arounds?

**Comment by jikamens** [comment]
Please see #669.
